var Icon = {
    "accessPoint": String.fromCodePoint(0xf0003),
    "calendar": String.fromCodePoint(0xf00ED),
    "calendarPlus": String.fromCodePoint(0xf00F3),
    "close": String.fromCodePoint(0xf0156),
    "map": String.fromCodePoint(0xf034D),
    "mapMarker": String.fromCodePoint(0xf034E),
    "mapMarkerDistance": String.fromCodePoint(0xf08F0),
    "mapSearch": String.fromCodePoint(0xf0984),
    "pageNext": String.fromCodePoint(0xf0BB0),
    "radar" : String.fromCodePoint(0xf0437),
    "reload": String.fromCodePoint(0xf0453),
    "share": String.fromCodePoint(0xf0496),
    "shareAll": String.fromCodePoint(0xf11F4),
    "shareVariant": String.fromCodePoint(0xf0497),
    "web": String.fromCodePoint(0xf059F),
    "wifi": String.fromCodePoint(0xf05A9),
}
